Small bugs I noticed
Hi Negar, as I was running your code I found a couple small things:
1. in line #14, you had `self.vocab = self.model.wv.vocab`, but I got: AttributeError: 'KeyedVectors' object has no attribute 'wv'. When I removed 'wv' everything is fine.
2. There's a typo "molar" which should be "moral" on line 17
3. on line 19 - 20 I think you forgot to read the mfd file? So I added that on, otherwise variable `mfd` is a string and I got error.